### ISSUE TITLE
Add comments from Judges

### ISSUE THREAD

**Issue by EnbangWu** [solodit/solodit_content#27]
Hi,

I am wondering if we can add the comments from Judges for C4 and Sherlock? There are several reasons to do so:

1. A lot of findings may seem similar at the first glance, they are quite different under their contexts. 
And judges are the ones to determine if a general vulnerability actually applies to this specific protocol. So it's good to know where the boundaries are.

2. I see oftentimes judges downgrading a finding because this and that. It would be helpful to know when a high turns into a med, and a med turns into a low. Auditors like me would love to learn the connections between bugs and vulnerabilities, grasp a high-level "bug flow". 

3. Sometimes there is even a battle between dev, auditor and judges. It'd be cool to see how a issue is handled and viewed in different perspectives.

Therefore, I think it will benefit auditors a lot and it's easy to implement ( I guess? just another optional subsection anyway.) Thank you.

**Comment by hans-cyfrin** [comment]
@EnbangWu 

Thanks for your suggestion and it makes sense to me.

But I am reluctant bringing those discussion into Solodit due to a few reasons.
- The discussion is not included in a published report technically. You can see some comments are included selectively.
- In a broader sense, this feature is about widening Solodit to include "communication during audit". And it's not possible for traditional audit firms.

I appreciate your suggestion anyway.
